# Generated by Django 4.2.5 on 2023-09-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_page',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Adınızı girin'),
        ),
    ]
