# Generated by Django 4.2.5 on 2023-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adınız')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email adres')),
                ('text', models.TextField(verbose_name='Tartışma başlığı')),
            ],
        ),
    ]
