# Generated by Django 4.2.5 on 2023-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_form_page_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_page',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adınızı girin'),
        ),
    ]
