# Generated by Django 4.2.5 on 2023-10-01 14:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_header_page_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_page',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='cate', unique=True),
        ),
    ]
